allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  keccak: true
  msgpackr-extract: true
  prisma: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
