import type { CommunityMember } from '@/types/member'

export const demoMember: CommunityMember = {
  id: 'alice',
  name: 'Alice Chen',
  role: 'Builder',
  tags: ['Participant', 'Helper'],
  avatarInitials: 'AC',
  communityId: 'adventurex',
  communityName: 'AdventureX Community',
  communityDescription: 'A builder community shaped by the people who keep showing up.',
  voicePower: {
    total: 1500,
    active: 1000,
    pending: 500,
    rankPercent: 15,
    earnedThisMonth: 550,
  },
  stats: {
    members: 25,
    activeProposals: 1,
    contributionsThisWeek: 12,
    trustedRecords: 4,
  },
  announcement: {
    title: 'Demo Night lineup is almost ready',
    body: 'Teams can still join mentor office hours before the final showcase.',
    createdAt: '2026-07-23',
  },
  nextEvent: {
    title: 'Mentor Office Hour',
    description: 'Bring your demo blockers and get feedback from mentors.',
    startsAt: '2026-07-24 19:00',
    location: 'AdventureX main hall',
    status: 'open',
  },
  activity: [
    {
      id: 'activity-demo-night',
      type: 'update',
      title: 'Demo Night lineup is almost ready',
      description: 'The operator shared the latest showcase order.',
      createdAt: '2026-07-23',
      status: 'new',
    },
    {
      id: 'activity-office-hour',
      type: 'event',
      title: 'Mentor Office Hour opened',
      description: 'Members can join tomorrow evening for demo feedback.',
      createdAt: '2026-07-23',
      status: 'active',
    },
    {
      id: 'activity-alpha-help',
      type: 'contribution',
      title: 'Alice helped Team Alpha test their demo',
      description: '+50 voice power approved by Jimmy.',
      createdAt: '2026-07-22',
      status: 'approved',
    },
    {
      id: 'activity-next-topic-vote',
      type: 'vote',
      title: 'Vote opened: next AdventureX event',
      description: 'Members can help choose the next community event theme.',
      createdAt: '2026-07-22',
      status: 'active',
    },
    {
      id: 'activity-trusted-record',
      type: 'record',
      title: 'Contribution reward record verified',
      description: 'A public receipt was created for the latest contribution batch.',
      createdAt: '2026-07-22',
      status: 'verified',
    },
  ],
  chatMessages: [
    {
      id: 'chat-jimmy-prompt',
      author: 'Jimmy',
      role: 'Operator',
      avatarInitials: 'JI',
      body: 'Demo Night lineup is almost ready. If your team needs feedback, join tomorrow office hour.',
      createdAt: '20:18',
      isOperator: true,
      reactions: 6,
    },
    {
      id: 'chat-alice',
      author: 'Alice Chen',
      role: 'Builder',
      avatarInitials: 'AC',
      body: 'Team Alpha still needs one more person to test their final flow. I can help after dinner.',
      createdAt: '20:21',
      isCurrentMember: true,
      reactions: 3,
    },
    {
      id: 'chat-carol',
      author: 'Carol',
      role: 'Mentor',
      avatarInitials: 'CA',
      body: 'I will be around for office hour. Bring a specific blocker so we can move fast.',
      createdAt: '20:25',
      reactions: 4,
    },
  ],
  featuredContributors: [
    {
      name: 'Dan',
      role: 'Organizer',
      voicePower: 800,
    },
    {
      name: 'Eve',
      role: 'Sponsor',
      voicePower: 600,
    },
    {
      name: 'Carol',
      role: 'Mentor',
      voicePower: 500,
    },
  ],
  contributions: [
    {
      id: 'contribution-demo-testing',
      title: 'Helped Team Alpha test their demo',
      description: 'Found a sign-in issue before demo day and shared a fix.',
      amount: 50,
      status: 'approved',
      activationStatus: 'active',
      approvedBy: 'Jimmy',
      createdAt: '2026-07-22',
      receipt: {
        id: 'receipt-alpha-help',
        title: 'Contribution reward verified',
        type: 'token_mint',
        status: 'verified',
        network: 'Injective Testnet',
        txHash: '0x7a8b9c2d4e5f6a1029384756abcdef1234567890',
        explorerUrl:
          'https://testnet.blockscout.injective.network/tx/0x7a8b9c2d4e5f6a1029384756abcdef1234567890',
        blockHeight: '#1,234,567',
        createdAt: '2026-07-22',
      },
    },
    {
      id: 'contribution-project-submission',
      title: 'Submitted AdventureX project',
      description: 'Completed and submitted a working product demo.',
      amount: 100,
      status: 'approved',
      activationStatus: 'active',
      approvedBy: 'Simon',
      createdAt: '2026-07-20',
    },
    {
      id: 'contribution-infrastructure',
      title: 'Built shared setup guide',
      description: 'Created a guide that helped new members deploy on Injective testnet.',
      amount: 500,
      status: 'approved',
      activationStatus: 'pending',
      approvedBy: 'Jimmy and Simon',
      createdAt: '2026-07-19',
    },
  ],
  availableProposals: [
    {
      id: 'next-event-topic',
      title: 'What should AdventureX host next?',
      description: 'Choose the next community event theme.',
      status: 'active',
      endsAt: '2026-07-25',
      snapshotWeight: 900,
      voterCount: 12,
      href: '/vote/next-event-topic',
    },
    {
      id: 'mentor-reward-rule',
      title: 'Should mentor rewards increase next month?',
      description: 'Update the reward rule for active mentors.',
      status: 'upcoming',
      endsAt: '2026-07-28',
      snapshotWeight: 1000,
      voterCount: 0,
      href: '/vote/mentor-reward-rule',
    },
    {
      id: 'showcase-layout',
      title: 'Which final showcase layout should we use?',
      description: 'Review the result from last week.',
      status: 'ended',
      endsAt: '2026-07-18',
      snapshotWeight: 1000,
      voterCount: 18,
      trustedRecordStatus: 'verified',
      href: '/vote/showcase-layout',
    },
  ],
  receipts: [
    {
      id: 'receipt-alpha-help',
      title: 'Contribution reward verified',
      type: 'token_mint',
      status: 'verified',
      network: 'Injective Testnet',
      txHash: '0x7a8b9c2d4e5f6a1029384756abcdef1234567890',
      explorerUrl:
        'https://testnet.blockscout.injective.network/tx/0x7a8b9c2d4e5f6a1029384756abcdef1234567890',
      blockHeight: '#1,234,567',
      createdAt: '2026-07-22',
    },
    {
      id: 'receipt-vote-snapshot',
      title: 'Vote snapshot recorded',
      type: 'proposal_snapshot',
      status: 'pending',
      network: 'Injective Testnet',
      createdAt: '2026-07-23',
    },
  ],
}

export function getDemoMember(communityId: string) {
  return {
    ...demoMember,
    communityId,
  }
}
