import type { CommunityMember } from '@/types/member'

export const demoMember: CommunityMember = {
  id: 'alice',
  name: 'Alice Chen',
  role: 'Builder',
  tags: ['Participant', 'Helper'],
  avatarInitials: 'AC',
  communityId: 'adventurex',
  communityName: 'AdventureX Community',
  communityDescription: 'A builder community shaped by the people who keep showing up.',
  voicePower: {
    total: 1500,
    active: 1000,
    pending: 500,
    rankPercent: 15,
    earnedThisMonth: 550,
  },
  stats: {
    members: 25,
    activeProposals: 1,
    contributionsThisWeek: 12,
    trustedRecords: 4,
  },
  announcement: {
    title: 'Demo Night lineup is almost ready',
    body: 'Teams can still join mentor office hours before the final showcase.',
    createdAt: '2026-07-23',
  },
  nextEvent: {
    title: 'Mentor Office Hour',
    description: 'Bring your demo blockers and get feedback from mentors.',
    startsAt: '2026-07-24 19:00',
    location: 'AdventureX main hall',
    status: 'open',
  },
  activity: [
    {
      id: 'activity-demo-night',
      type: 'update',
      title: 'Demo Night lineup is almost ready',
      description: 'The operator shared the latest showcase order.',
      createdAt: '2026-07-23',
      status: 'new',
    },
    {
      id: 'activity-office-hour',
      type: 'event',
      title: 'Mentor Office Hour opened',
      description: 'Members can join tomorrow evening for demo feedback.',
      createdAt: '2026-07-23',
      status: 'active',
    },
    {
      id: 'activity-alpha-help',
      type: 'contribution',
      title: 'Alice helped Team Alpha test their demo',
      description: '+50 voice power approved by Jimmy.',
      createdAt: '2026-07-22',
      status: 'approved',
    },
    {
      id: 'activity-next-topic-vote',
      type: 'vote',
      title: 'Vote opened: next AdventureX event',
      description: 'Members can help choose the next community event theme.',
      createdAt: '2026-07-22',
      status: 'active',
    },
    {
      id: 'activity-trusted-record',
      type: 'record',
      title: 'Contribution reward record verified',
      description: 'A public receipt was created for the latest contribution batch.',
      createdAt: '2026-07-22',
      status: 'verified',
    },
  ],
  chatMessages: [
    {
      id: 'chat-jimmy-prompt',
      author: 'Jimmy',
      role: 'Operator',
      avatarInitials: 'JI',
      body: 'Demo Night lineup is almost ready. If your team needs feedback, join tomorrow office hour.',
      createdAt: '20:18',
      isOperator: true,
      reactions: 6,
    },
    {
      id: 'chat-alice',
      author: 'Alice Chen',
      role: 'Builder',
      avatarInitials: 'AC',
      body: 'Team Alpha still needs one more person to test their final flow. I can help after dinner.',
      createdAt: '20:21',
      isCurrentMember: true,
      reactions: 3,
    },
    {
      id: 'chat-carol',
      author: 'Carol',
      role: 'Mentor',
      avatarInitials: 'CA',
      body: 'I will be around for office hour. Bring a specific blocker so we can move fast.',
      createdAt: '20:25',
      reactions: 4,
    },
  ],
  chatRooms: [
    {
      id: 'adventurex-main',
      title: 'AdventureX Main',
      description: 'General updates, quick asks, and community coordination.',
      avatarInitials: 'AX',
      category: 'Community',
      unreadCount: 4,
      muted: false,
      pinned: true,
      updatedAt: '20:25',
      inviteCode: 'youfen.gg/adventurex-main',
      sharedMediaCount: 18,
      lastMessage: {
        author: 'Carol',
        body: 'Bring a specific blocker so we can move fast.',
      },
      participants: [
        {
          id: 'jimmy',
          name: 'Jimmy',
          role: 'Operator',
          avatarInitials: 'JI',
          status: 'online',
          isOperator: true,
        },
        {
          id: 'alice',
          name: 'Alice Chen',
          role: 'Builder',
          avatarInitials: 'AC',
          status: 'online',
        },
        {
          id: 'carol',
          name: 'Carol',
          role: 'Mentor',
          avatarInitials: 'CA',
          status: 'online',
        },
        {
          id: 'dan',
          name: 'Dan',
          role: 'Organizer',
          avatarInitials: 'DA',
          status: 'offline',
          lastSeen: '18:40',
        },
        {
          id: 'eve',
          name: 'Eve',
          role: 'Sponsor',
          avatarInitials: 'EV',
          status: 'offline',
          lastSeen: 'Yesterday',
        },
      ],
      messages: [
        {
          id: 'main-jimmy-prompt',
          author: 'Jimmy',
          role: 'Operator',
          avatarInitials: 'JI',
          body: 'Demo Night lineup is almost ready. If your team needs feedback, join tomorrow office hour.',
          createdAt: '20:18',
          isOperator: true,
          reactions: 6,
        },
        {
          id: 'main-alice-help',
          author: 'Alice Chen',
          role: 'Builder',
          avatarInitials: 'AC',
          body: 'Team Alpha still needs one more person to test their final flow. I can help after dinner.',
          createdAt: '20:21',
          isCurrentMember: true,
          reactions: 3,
        },
        {
          id: 'main-carol-office-hour',
          author: 'Carol',
          role: 'Mentor',
          avatarInitials: 'CA',
          body: 'I will be around for office hour. Bring a specific blocker so we can move fast.',
          createdAt: '20:25',
          reactions: 4,
        },
      ],
    },
    {
      id: 'demo-night-crew',
      title: 'Demo Night Crew',
      description: 'Run-of-show, stage timing, volunteers, and final checks.',
      avatarInitials: 'DN',
      category: 'Event',
      unreadCount: 2,
      muted: false,
      pinned: true,
      updatedAt: '19:48',
      inviteCode: 'youfen.gg/demo-night-crew',
      sharedMediaCount: 7,
      lastMessage: {
        author: 'Dan',
        body: 'I updated the check-in sheet and marked the late teams.',
      },
      participants: [
        {
          id: 'jimmy',
          name: 'Jimmy',
          role: 'Operator',
          avatarInitials: 'JI',
          status: 'online',
          isOperator: true,
        },
        {
          id: 'alice',
          name: 'Alice Chen',
          role: 'Builder',
          avatarInitials: 'AC',
          status: 'online',
        },
        {
          id: 'dan',
          name: 'Dan',
          role: 'Organizer',
          avatarInitials: 'DA',
          status: 'online',
        },
        {
          id: 'mira',
          name: 'Mira',
          role: 'Volunteer',
          avatarInitials: 'MI',
          status: 'offline',
          lastSeen: '19:05',
        },
      ],
      messages: [
        {
          id: 'demo-jimmy-run-of-show',
          author: 'Jimmy',
          role: 'Operator',
          avatarInitials: 'JI',
          body: 'Pinned checklist: final deck order, stage timer, check-in desk, and photo corner.',
          createdAt: '19:32',
          isOperator: true,
          reactions: 8,
        },
        {
          id: 'demo-alice-signage',
          author: 'Alice Chen',
          role: 'Builder',
          avatarInitials: 'AC',
          body: 'I can help print the QR sign for the public receipt page.',
          createdAt: '19:41',
          isCurrentMember: true,
          reactions: 2,
        },
        {
          id: 'demo-dan-check-in',
          author: 'Dan',
          role: 'Organizer',
          avatarInitials: 'DA',
          body: 'I updated the check-in sheet and marked the late teams.',
          createdAt: '19:48',
          reactions: 1,
        },
      ],
    },
    {
      id: 'mentor-office-hour',
      title: 'Mentor Office Hour',
      description: 'Book feedback, share blockers, and match mentors with teams.',
      avatarInitials: 'MO',
      category: 'Mentors',
      unreadCount: 0,
      muted: true,
      pinned: false,
      updatedAt: '18:12',
      inviteCode: 'youfen.gg/mentor-office',
      sharedMediaCount: 5,
      lastMessage: {
        author: 'Carol',
        body: 'Drop your blocker before the session so mentors can prepare.',
      },
      participants: [
        {
          id: 'carol',
          name: 'Carol',
          role: 'Mentor',
          avatarInitials: 'CA',
          status: 'online',
        },
        {
          id: 'alice',
          name: 'Alice Chen',
          role: 'Builder',
          avatarInitials: 'AC',
          status: 'online',
        },
        {
          id: 'nate',
          name: 'Nate',
          role: 'Builder',
          avatarInitials: 'NA',
          status: 'offline',
          lastSeen: '17:55',
        },
        {
          id: 'zoe',
          name: 'Zoe',
          role: 'Mentor',
          avatarInitials: 'ZO',
          status: 'offline',
          lastSeen: 'Yesterday',
        },
      ],
      messages: [
        {
          id: 'mentor-carol-prompt',
          author: 'Carol',
          role: 'Mentor',
          avatarInitials: 'CA',
          body: 'Drop your blocker before the session so mentors can prepare.',
          createdAt: '18:02',
          isOperator: true,
          reactions: 5,
        },
        {
          id: 'mentor-alice-flow',
          author: 'Alice Chen',
          role: 'Builder',
          avatarInitials: 'AC',
          body: 'I want feedback on onboarding. People understand the value, but the first action is unclear.',
          createdAt: '18:07',
          isCurrentMember: true,
        },
        {
          id: 'mentor-nate-demo',
          author: 'Nate',
          role: 'Builder',
          avatarInitials: 'NA',
          body: 'Can someone review a 90-second demo script before tonight?',
          createdAt: '18:12',
          reactions: 2,
        },
      ],
    },
    {
      id: 'team-alpha-help',
      title: 'Team Alpha Help',
      description: 'Small group for testing, bug reports, and demo polish.',
      avatarInitials: 'TA',
      category: 'Project',
      unreadCount: 0,
      muted: false,
      pinned: false,
      updatedAt: '17:36',
      inviteCode: 'youfen.gg/team-alpha-help',
      sharedMediaCount: 11,
      lastMessage: {
        author: 'Alice Chen',
        body: 'I found the mobile sign-in bug. The fix is in the thread above.',
      },
      participants: [
        {
          id: 'alice',
          name: 'Alice Chen',
          role: 'Builder',
          avatarInitials: 'AC',
          status: 'online',
        },
        {
          id: 'liam',
          name: 'Liam',
          role: 'Builder',
          avatarInitials: 'LI',
          status: 'online',
        },
        {
          id: 'mira',
          name: 'Mira',
          role: 'Volunteer',
          avatarInitials: 'MI',
          status: 'offline',
          lastSeen: '17:50',
        },
      ],
      messages: [
        {
          id: 'alpha-liam-ask',
          author: 'Liam',
          role: 'Builder',
          avatarInitials: 'LI',
          body: 'Can someone test sign-in on a small Android screen?',
          createdAt: '17:21',
          reactions: 1,
        },
        {
          id: 'alpha-alice-bug',
          author: 'Alice Chen',
          role: 'Builder',
          avatarInitials: 'AC',
          body: 'I found the mobile sign-in bug. The fix is in the thread above.',
          createdAt: '17:36',
          isCurrentMember: true,
          reactions: 4,
        },
      ],
    },
  ],
  featuredContributors: [
    {
      name: 'Dan',
      role: 'Organizer',
      voicePower: 800,
    },
    {
      name: 'Eve',
      role: 'Sponsor',
      voicePower: 600,
    },
    {
      name: 'Carol',
      role: 'Mentor',
      voicePower: 500,
    },
  ],
  contributions: [
    {
      id: 'contribution-demo-testing',
      title: 'Helped Team Alpha test their demo',
      description: 'Found a sign-in issue before demo day and shared a fix.',
      amount: 50,
      status: 'approved',
      activationStatus: 'active',
      approvedBy: 'Jimmy',
      createdAt: '2026-07-22',
      receipt: {
        id: 'receipt-alpha-help',
        title: 'Contribution reward verified',
        type: 'token_mint',
        status: 'verified',
        network: 'Injective Testnet',
        txHash: '0x7a8b9c2d4e5f6a1029384756abcdef1234567890',
        explorerUrl:
          'https://testnet.blockscout.injective.network/tx/0x7a8b9c2d4e5f6a1029384756abcdef1234567890',
        blockHeight: '#1,234,567',
        createdAt: '2026-07-22',
      },
    },
    {
      id: 'contribution-project-submission',
      title: 'Submitted AdventureX project',
      description: 'Completed and submitted a working product demo.',
      amount: 100,
      status: 'approved',
      activationStatus: 'active',
      approvedBy: 'Simon',
      createdAt: '2026-07-20',
    },
    {
      id: 'contribution-infrastructure',
      title: 'Built shared setup guide',
      description: 'Created a guide that helped new members deploy on Injective testnet.',
      amount: 500,
      status: 'approved',
      activationStatus: 'pending',
      approvedBy: 'Jimmy and Simon',
      createdAt: '2026-07-19',
    },
  ],
  availableProposals: [
    {
      id: 'next-event-topic',
      title: 'What should AdventureX host next?',
      description: 'Choose the next community event theme.',
      status: 'active',
      endsAt: '2026-07-25',
      snapshotWeight: 900,
      voterCount: 12,
      href: '/vote/next-event-topic',
    },
    {
      id: 'mentor-reward-rule',
      title: 'Should mentor rewards increase next month?',
      description: 'Update the reward rule for active mentors.',
      status: 'upcoming',
      endsAt: '2026-07-28',
      snapshotWeight: 1000,
      voterCount: 0,
      href: '/vote/mentor-reward-rule',
    },
    {
      id: 'showcase-layout',
      title: 'Which final showcase layout should we use?',
      description: 'Review the result from last week.',
      status: 'ended',
      endsAt: '2026-07-18',
      snapshotWeight: 1000,
      voterCount: 18,
      trustedRecordStatus: 'verified',
      href: '/vote/showcase-layout',
    },
  ],
  receipts: [
    {
      id: 'receipt-alpha-help',
      title: 'Contribution reward verified',
      type: 'token_mint',
      status: 'verified',
      network: 'Injective Testnet',
      txHash: '0x7a8b9c2d4e5f6a1029384756abcdef1234567890',
      explorerUrl:
        'https://testnet.blockscout.injective.network/tx/0x7a8b9c2d4e5f6a1029384756abcdef1234567890',
      blockHeight: '#1,234,567',
      createdAt: '2026-07-22',
    },
    {
      id: 'receipt-vote-snapshot',
      title: 'Vote snapshot recorded',
      type: 'proposal_snapshot',
      status: 'pending',
      network: 'Injective Testnet',
      createdAt: '2026-07-23',
    },
  ],
}

export function getDemoMember(communityId: string) {
  return {
    ...demoMember,
    communityId,
  }
}
