-- Drop all tables first
DROP TABLE IF EXISTS "ProposalExecution" CASCADE;
DROP TABLE IF EXISTS "MemberChainBalance" CASCADE;
DROP TABLE IF EXISTS "MemberEpochMintCounter" CASCADE;
DROP TABLE IF EXISTS "TokenRuleVersion" CASCADE;
DROP TABLE IF EXISTS "SyncCheckpoint" CASCADE;
DROP TABLE IF EXISTS "ChainEvent" CASCADE;
DROP TABLE IF EXISTS "ChainTransaction" CASCADE;
DROP TABLE IF EXISTS "ChainAction" CASCADE;
DROP TABLE IF EXISTS "Signature" CASCADE;
DROP TABLE IF EXISTS "SignatureRequest" CASCADE;
DROP TABLE IF EXISTS "CommunityApprover" CASCADE;
DROP TABLE IF EXISTS "CommunityController" CASCADE;
DROP TABLE IF EXISTS "SignerChallenge" CASCADE;
DROP TABLE IF EXISTS "MemberSigner" CASCADE;
DROP TABLE IF EXISTS "ProposalMemberSnapshot" CASCADE;
DROP TABLE IF EXISTS "Vote" CASCADE;
DROP TABLE IF EXISTS "TokenPolicyVersion" CASCADE;
DROP TABLE IF EXISTS "TokenAdvanceRequest" CASCADE;
DROP TABLE IF EXISTS "Contribution" CASCADE;
DROP TABLE IF EXISTS "IdempotencyKey" CASCADE;
DROP TABLE IF EXISTS "MemberTokenBalance" CASCADE;
DROP TABLE IF EXISTS "CommunityTokenState" CASCADE;
DROP TABLE IF EXISTS "TokenReversalEvent" CASCADE;
DROP TABLE IF EXISTS "TokenMintEvent" CASCADE;
DROP TABLE IF EXISTS "TokenEpoch" CASCADE;
DROP TABLE IF EXISTS "CommunityTokenPolicy" CASCADE;
DROP TABLE IF EXISTS "Member" CASCADE;
DROP TABLE IF EXISTS "Community" CASCADE;
DROP TABLE IF EXISTS "PublicRecord" CASCADE;

-- Drop enums
DROP TYPE IF EXISTS "SignatureRole" CASCADE;
DROP TYPE IF EXISTS "ChainActionStatus" CASCADE;
DROP TYPE IF EXISTS "ChainActionKind" CASCADE;
DROP TYPE IF EXISTS "PublicRecordType" CASCADE;
DROP TYPE IF EXISTS "VerificationStatus" CASCADE;
